export const API_PATHS = {
  login: '/api/v1/auth/login',
  me: '/api/v1/auth/me',
  users: '/api/v1/users',
  equipment: '/api/v1/equipment',
  equipmentDetail: (id: number | string) => `/api/v1/equipment/${id}`,
  equipmentStatus: (id: number | string) => `/api/v1/equipment/${id}/status`,
  equipmentOwner: (id: number | string) => `/api/v1/equipment/${id}/owner`,
  borrows: '/api/v1/borrows',
  borrowDetail: (id: number | string) => `/api/v1/borrows/${id}`,
  borrowApprove: (id: number | string) => `/api/v1/borrows/${id}/approve`,
  borrowReject: (id: number | string) => `/api/v1/borrows/${id}/reject`,
  borrowReturn: (id: number | string) => `/api/v1/borrows/${id}/return`,
  maintenance: '/api/v1/maintenance',
  maintenanceStats: '/api/v1/maintenance/stats',
  maintenanceExecute: (id: number | string) => `/api/v1/maintenance/${id}/execute`,
  reservations: '/api/v1/reservations',
  reservationDetail: (id: number | string) => `/api/v1/reservations/${id}`,
  reservationApprove: (id: number | string) => `/api/v1/reservations/${id}/approve`,
  reservationReject: (id: number | string) => `/api/v1/reservations/${id}/reject`,
  reservationCancel: (id: number | string) => `/api/v1/reservations/${id}/cancel`,
  categories: '/api/v1/categories',
  dashboardStats: '/api/v1/dashboard/stats',
  auditLogs: '/api/v1/audit-logs'
} as const
